language: go
go:
  - 1.15.x

before_install:
  - source ~/.nvm/nvm.sh
  - nvm install 14

jobs:
  include:
    - name: Lint
      script: make lint
    - name: Test
      script: make test
    - name: Build Docker image
      script: make docker
      services:
        - docker
    - name: Release
      stage: github-pages
      if: branch = master AND type = push
      script:
        - docker build -t go-wasm .
        - docker cp $(docker create --rm go-wasm):/usr/share/nginx/html ./public
      services:
        - docker
      deploy:
        provider: pages
        fqdn: go-wasm.johnstarich.com
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: ./public
